apiVersion: v1
kind: Secret
metadata:
  name: codestorm-secrets
type: Opaque
stringData:
  DB_HOST: "codestorm-prod-db.c5wu6ogwub2g.ap-south-1.rds.amazonaws.com"
  DB_USER: "codestorm_admin"
  DB_PASSWORD: "sqlkabaap"
  DB_NAME: "cloudjudge"
  JWT_SECRET: "cloudjudge_secret_key_2024"
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/673515369025/codestorm-prod-queue"
  S3_BUCKET_NAME: "codestorm-prod-submissions-77eb53a3"
  AWS_REGION: "ap-south-1"
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  EMAIL_USER: "tammineedinavaneeth@gmail.com"
  EMAIL_PASS: "rgkhddtvtapdjubr"
